language: shell
os: linux
dist: bionic


addons:
  apt:
    packages:
    - curl
    - ffmpeg
    - wget
    
script:
    - sudo sh -c "mkdir /video && chown "$(whoami):"$(whoami) /video" && cd /video

#   ---TRANSCODE---
    - ffmpeg -i "https://proxy-16.nyc.dailymotion.com/sec(jRUWpB4i4BTcBhaSBTsVm-iDeRwMrHUXNtiak1eeSC3jJKlcXXW9DRcQMFlEI0B4PZ5VFshOV2JHoyNxcAYfhzGUid7PtV3MVsjJ5bqyfto)/video/594/502/482205495_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_116_-_Catalina_le_dara_un_giro_inesperado_a_la_vida_de_Betty.mp4"
    - ffmpeg -i "https://proxy-18.nyc.dailymotion.com/sec(eUr04nlHUdL_H2XQBfZlD17osjnV_tfTeYq-LbM1DEzlXBNiX4y-hzqUax7DhQYO_9Bql0kLM20sSCV03IYVYHUstldVjtflokaBfowTLFk)/video/567/542/482245765_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_117_-_Betty_sorprende_a_todos_al_lucir_un_nuevo_look.mp4"
    - ffmpeg -i "https://proxy-03.nyc.dailymotion.com/sec(No_TQeY4Fy-YPTx9YHcvG8DLUDGn92C9b_3cnnFz_fM5JceMdDaogYnIU7Yez69BUgnW463lgIuVfIMlaRrMbqcpTDsNHAGVdynu9SF40g8)/video/195/292/482292591_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_118_-_Betty_pasa_una_magica_noche_con_Michel.mp4"
    - ffmpeg -i "https://proxy-16.nyc.dailymotion.com/sec(zvUbbWr2oKyjb9WcqKTKNbREU47hiGP647XQGdWUxQpBScXiR_OmjXmraw9kSoOtYYYEqyXzlzqml0i0mRlNOGnKLpNiBl0zc9kxqHeq3zE)/video/272/773/482377272_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_119_-_Armando_le_confirma_a_su_mama_que_esta_enamorado_de_Betty.mp4"
    - ffmpeg -i "https://proxy-22.nyc.dailymotion.com/sec(f2DpPaaM8u15Kq2lKySPGF-U6QDdYWs4w2IGmNxX01u5Pi6MUK9zaqlzm8pyRYkMYCUrG7Gr2cz00jyC2vgIljc1E9yafbAYPdJDeBo6_MM)/video/814/914/482419418_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_120_-_Betty_va_a_la_peluqueria_y_deslumbra_a_Michel_con_su_cambio.mp4"
    - ffmpeg -i "https://proxy-14.nyc.dailymotion.com/sec(6KQ917mD1-x0Bqudp7rLfE97uqqOyXJWm5v_VTN91fEosoGeS26uUfXMA-CaC74GTjZ3sJIhzsGumY8i-B3Ch3C1I1Xs1upS0kwFuWYehok)/video/897/054/482450798_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_121_-_Michel_intenta_besar_a_Betty.mp4"
    - ffmpeg -i "https://proxy-13.nyc.dailymotion.com/sec(4D9qlkTX-vRCFXZHYHjCmssjQ5j2CFIkvN4imwCB97mKXf-F0mM89_uoKr3qz_50hmvoR-cs_P-UuygYdUx5l-CU_eDycV1ti9AEifManw8)/video/069/884/482488960_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_122_-_Julia_le_reclama_a_Armando_por_lo_que_le_hizo_a_Betty.mp4"

#    - ffmpeg -i "" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 ""$" 
#   ---UPLOAD---
    - curl --upload-file ./Capitulo_116_-_Catalina_le_dara_un_giro_inesperado_a_la_vida_de_Betty.mp4 http://transfer.sh/
    - curl --upload-file ./Capitulo_117_-_Betty_sorprende_a_todos_al_lucir_un_nuevo_look.mp4 http://transfer.sh/
    - curl --upload-file ./Capitulo_118_-_Betty_pasa_una_magica_noche_con_Michel.mp4 http://transfer.sh/
    - curl --upload-file ./Capitulo_119_-_Armando_le_confirma_a_su_mama_que_esta_enamorado_de_Betty.mp4 http://transfer.sh/
    - curl --upload-file ./Capitulo_120_-_Betty_va_a_la_peluqueria_y_deslumbra_a_Michel_con_su_cambio.mp4 http://transfer.sh/
    - curl --upload-file ./Capitulo_121_-_Michel_intenta_besar_a_Betty.mp4 http://transfer.sh/
    - curl --upload-file ./Capitulo_122_-_Julia_le_reclama_a_Armando_por_lo_que_le_hizo_a_Betty.mp4 http://transfer.sh/

#
#    - curl --upload-file ./$CXPX http://transfer.sh/