language: shell
os: linux
dist: bionic


addons:
  apt:
    packages:
    - curl
    - ffmpeg
    - wget
    
script:
    - sudo sh -c "mkdir /video && chown "$(whoami):"$(whoami) /video" && cd /video

#   ---TRANSCODE---
#    - ffmpeg -i "" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "Capitulo_123_-_Michel_le_pide_perdon_a_Betty_y_le_hace_una_gran_confesion.mp4"
#   ---UPLOAD---
#    - curl --upload-file ./Capitulo_123_-_Michel_le_pide_perdon_a_Betty_y_le_hace_una_gran_confesion.mp4 http://transfer.sh/
#   ---2WEBDAV---
    - wget http://transfer.sh/PreO2/Capitulo_115_-_Armando_le_confiesa_a_Marcela_que_se_enamoro_de_Betty.mp4
    - wget http://transfer.sh/TGH0m/Capitulo_116_-_Catalina_le_dara_un_giro_inesperado_a_la_vida_de_Betty.mp4
    - wget http://transfer.sh/EjzVR/Capitulo_117_-_Betty_sorprende_a_todos_al_lucir_un_nuevo_look.mp4
    - wget http://transfer.sh/Ajvvp/Capitulo_118_-_Betty_pasa_una_magica_noche_con_Michel.mp4
    - wget http://transfer.sh/tPaR7/Capitulo_119_-_Armando_le_confirma_a_su_mama_que_esta_enamorado_de_Betty.mp4
    - wget http://transfer.sh/2hjnq/Capitulo_120_-_Betty_va_a_la_peluqueria_y_deslumbra_a_Michel_con_su_cambio.mp4
    - wget http://transfer.sh/HstQ2/Capitulo_121_-_Michel_intenta_besar_a_Betty.mp4
    - wget http://transfer.sh/Gd2uV/Capitulo_122_-_Julia_le_reclama_a_Armando_por_lo_que_le_hizo_a_Betty.mp4
    - wget http://transfer.sh/7pOUB/Capitulo_123_-_Michel_le_pide_perdon_a_Betty_y_le_hace_una_gran_confesion.mp4
    - wget http://transfer.sh/ooJwH/Capitulo_124_-_Betty_perdona_a_Armando.mp4
    - wget http://transfer.sh/mtT52/Capitulo_125_-_Don_Hermes_no_se_queda_con_los_brazos_cruzados_y_va_a_Ecomoda.mp4
    - wget http://transfer.sh/Eru2u/Capitulo_126_-_Betty_sorprende_a_sus_papas_con_su_cambio_de_look.mp4
    - wget http://transfer.sh/11sW36/Capitulo_127_-_Betty_acepta_ir_a_Ecomoda.mp4
    - wget http://transfer.sh/12KEb1/Capitulo_128_-_La_emocionante_llegada_de_Betty_a_Ecomoda.mp4

    - curl -T Capitulo_115_-_Armando_le_confiesa_a_Marcela_que_se_enamoro_de_Betty.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_115_-_Armando_le_confiesa_a_Marcela_que_se_enamoro_de_Betty.mp4
    - curl -T Capitulo_116_-_Catalina_le_dara_un_giro_inesperado_a_la_vida_de_Betty.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_116_-_Catalina_le_dara_un_giro_inesperado_a_la_vida_de_Betty.mp4
    - curl -T Capitulo_117_-_Betty_sorprende_a_todos_al_lucir_un_nuevo_look.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_117_-_Betty_sorprende_a_todos_al_lucir_un_nuevo_look.mp4
    - curl -T Capitulo_118_-_Betty_pasa_una_magica_noche_con_Michel.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_118_-_Betty_pasa_una_magica_noche_con_Michel.mp4
    - curl -T Capitulo_119_-_Armando_le_confirma_a_su_mama_que_esta_enamorado_de_Betty.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_119_-_Armando_le_confirma_a_su_mama_que_esta_enamorado_de_Betty.mp4
    - curl -T Capitulo_120_-_Betty_va_a_la_peluqueria_y_deslumbra_a_Michel_con_su_cambio.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_120_-_Betty_va_a_la_peluqueria_y_deslumbra_a_Michel_con_su_cambio.mp4
    - curl -T Capitulo_121_-_Michel_intenta_besar_a_Betty.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_121_-_Michel_intenta_besar_a_Betty.mp4
    - curl -T Capitulo_122_-_Julia_le_reclama_a_Armando_por_lo_que_le_hizo_a_Betty.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_122_-_Julia_le_reclama_a_Armando_por_lo_que_le_hizo_a_Betty.mp4
    - curl -T Capitulo_123_-_Michel_le_pide_perdon_a_Betty_y_le_hace_una_gran_confesion.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_123_-_Michel_le_pide_perdon_a_Betty_y_le_hace_una_gran_confesion.mp4
    - curl -T Capitulo_124_-_Betty_perdona_a_Armando.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_124_-_Betty_perdona_a_Armando.mp4
    - curl -T Capitulo_125_-_Don_Hermes_no_se_queda_con_los_brazos_cruzados_y_va_a_Ecomoda.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_125_-_Don_Hermes_no_se_queda_con_los_brazos_cruzados_y_va_a_Ecomoda.mp4
    - curl -T Capitulo_126_-_Betty_sorprende_a_sus_papas_con_su_cambio_de_look.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_126_-_Betty_sorprende_a_sus_papas_con_su_cambio_de_look.mp4
    - curl -T Capitulo_127_-_Betty_acepta_ir_a_Ecomoda.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_127_-_Betty_acepta_ir_a_Ecomoda.mp4
    - curl -T Capitulo_128_-_La_emocionante_llegada_de_Betty_a_Ecomoda.mp4 -u juanliz:C%9Z2p6c6RqD https://ftp.cdnrobot.xyz/webdav/YSBLF-2020/Capitulo_128_-_La_emocionante_llegada_de_Betty_a_Ecomoda.mp4
    